version: 2

sources:
  - name: results
    database: "{{ env_var('DBT_GCLOUD_PROJECT') }}"
    schema: "{{ env_var('DBT_BQ_DATASET') }}"
    tables:
      - name: ticket_data_sentiment_analysis

models:
  - name: zendesk_ticket_descriptions
    description: zendesk ticket descriptions
    config:
      materialized: table
    meta:
      owner: "@meder"
      fal:
        scripts:
          - fal_scripts/slack.py
